### ISSUE TITLE
Redundant steer to "visit review" when duplicate module review is entered

### ISSUE THREAD

**Issue by ruthsykes** [world-class/compass#72]
Journey:
1. Already reviewed ITP1
2. Go to Courses and select ITP1 again (and fill in other boxes with valid input)
3. Hit Submit
4. My original review is presented to me (not the new review), however this page also has "You have already reviewed this course. Would you like to edit it? Visit review" link on it which is redundant, as I am already there.

Suggest after hitting Submit, the new review remains on the page, in case the user has selected the wrong module by accident. Then their text isn't lost.

**Comment by BlairCurrey** [comment]
Thanks for the suggestion Ruth. I agree with your suggestion. In addition I think we should flash a message indicating they have already reviewed the course and add a link that takes them to the edit review.

For some more context, the `visit review` link is hardcoded into the flash message in the `editreview.html` template. It will always show a link to the review regardless of the message. This was originally implemented so that you would have a link after editing so that you could see the review - however, it's not always that relevant (such as this situation). Ideally it should probably be part of the message sent from the server but it wasn't clear to me how to ensure it rendered as link instead of text.
